name: Sync Develop to Main

on:
  push:
    branches:
      - develop

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: refs/heads/main
          persist-credentials: false
          fetch-depth: 0

      - name: Merge Develop into Main
        run: |
          git checkout main
          git merge develop
          git push origin main
